functionsDirectory = "/Users/david2/.openclaw/workspace/interesting-america-hp/netlify/functions"
functionsDirectoryOrigin = "ui"
plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/david2/.openclaw/workspace/interesting-america-hp/_site"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"
functions = "/Users/david2/.openclaw/workspace/interesting-america-hp/netlify/functions"

[build.environment]
NODE_VERSION = "20"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]