name = "ia-cms-oauth"
main = "worker.js"
compatibility_date = "2026-03-15"

[[kv_namespaces]]
binding = "TERMS_CONFIRMATIONS_KV"
id = "34364213c42447959f2235af7f7199cd"
# preview_id = "REPLACE_WITH_PREVIEW_KV_NAMESPACE_ID"

[vars]
ALLOWED_ORIGIN = "https://xtradmk.github.io"
GITHUB_CLIENT_ID = "Ov23lihgQkJGG0k8CBH9"
ADDITIONAL_ALLOWED_ORIGINS = "https://interesting-america.com,https://www.interesting-america.com,https://interestingamerica.com,https://www.interestingamerica.com,http://localhost:8080,http://127.0.0.1:8080"
DISCORD_CHANNEL_ID = "1504043044834381866"
